In [1]:
import pandas as pd
import numpy as np
import re
import nltk

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Ayush\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ayush\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
df = pd.read_csv("data/gutenberg_novels_dataset.csv")

In [4]:
df.head()

,gutenberg_id,title,author,download_url,text_length,text
0,1342,Pride and Prejudice,Jane Austen,https://www.gutenberg.org/files/1342/1342-0.txt,728392,*** START OF THE PROJECT GUTENBERG EBOOK 1342 ...
1,84,Frankenstein,Mary Shelley,https://www.gutenberg.org/files/84/84-0.txt,419290,*** START OF THE PROJECT GUTENBERG EBOOK 84 **...
2,345,Dracula,Bram Stoker,https://www.gutenberg.org/files/345/345-0.txt,845805,*** START OF THE PROJECT GUTENBERG EBOOK 345 *...

In [9]:
df = df[['text']]

In [10]:
df.shape

(3, 1)

In [17]:
df['text'].isnull().sum()

np.int64(0)

In [28]:
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
ss= SnowballStemmer("english")
y= []
for i in range(0,len(df['text'])):
    x = re.sub('[^a-zA-Z]',' ',df["text"][i])
    x = x.lower()
    x = x.split()
    x = [ss.stem(word) for word in x if not word in stopwords.words('english')]
    x = ' '.join(x)
    y.append(x)
df['clean_text']=y

In [29]:
df.head()

,text,clean_text
0,*** START OF THE PROJECT GUTENBERG EBOOK 1342 ...,start project gutenberg ebook illustr georg al...
1,*** START OF THE PROJECT GUTENBERG EBOOK 84 **...,start project gutenberg ebook frankenstein mod...
2,*** START OF THE PROJECT GUTENBERG EBOOK 345 *...,start project gutenberg ebook dracula bram sto...

In [30]:
corpus = " ".join(df['clean_text'].values)

print("Total Characters:", len(corpus))
print("Sample:\n", corpus[:500])

Total Characters: 1007431
Sample:
 start project gutenberg ebook illustr georg allen publish chare cross road london ruskin hous illustr read jane letter chap pride prejudic jane austen prefac georg saintsburi illustr hugh thomson illustr ruskin chare hous cross road london georg allen chiswick press charl whittingham co took court chanceri lane london illustr j comyn carr acknowledg owe friendship advic illustr grate inscrib hugh thomson prefac illustr walt whitman somewher fine distinct love allow love person love distinct appl

In [32]:
with open("data/cleaned_corpus.txt", "w", encoding="utf-8") as f:
    f.write(corpus)

print("Cleaned corpus saved successfully.")

Cleaned corpus saved successfully.